# #######################################################################################
# HYPRPAPER CONFIG.
# #######################################################################################

preload = ~/.config/wallpaper.jpg

wallpaper = ,~/.config/wallpaper.jpg

# splash = true

#fully disable ipc
ipc = off

