# #######################################################################################
# HYPRPAPER CONFIG.
# #######################################################################################

preload = /home/kabdelhalem/.config/wallpaper.jpg

wallpaper = ,/home/kabdelhalem/.config/wallpaper.jpg

# splash = true

#fully disable ipc
#ipc = off

